import Head from 'next/head'
import React from 'react'
import Footer from '../components/Footer'
import Header from '../components/Header'

export default function Termsandcondition() {
    return (
        <div>
            <Head>
                <title>Energize EV Charging Solutions - Terms and condition</title>
                <link rel='shortcut icon' href='/favicon.ico' />
            </Head>
            <div className='px-10 max-w-[1238px] mx-auto'>
                <Header />
                <div className='mt-10 max-w-[1000px] mx-auto'>
                    <div className='font-bold text-center'>Terms and Conditions of Usage</div>
                    <p>Welcome to 'Energize' app/platform.
                        Energize EV Charging Solutions ("Energize" or "Service Provider") provides access to
                        'Energize' app/ platform to you subject to the terms and conditions set out below on this
                        page. This document shall use the term 'Platform' which will be applicable to both mobile
                        app and web portal.</p>
                    <b>1. Terms</b>
                    <p>These "Terms and Conditions" ("Terms") of usage constitute an electronic record within
                        the meaning of the applicable law. This electronic record is generated by a computer
                        system and does not require any physical or digital signatures. These Terms read with the
                        Privacy Policy, Disclaimers, as may be published on this Platform and updated from time
                        to time, shall govern your use / access to the Platform, its related content, sites and
                        hyperlinks owned, maintained and operated by Energize, its subsidiaries and its affiliates.
                        These Terms apply to all users of the Platform.
                        Please read these conditions carefully before using the Platform. By using the Platform,
                        you agree to be bound by these Terms. By implicitly or expressly accepting these Terms,
                        Privacy Policy, you also accept and agree to be bound by Rules, Policies and Terms of
                        Energize as published on this Platform from time to time and corresponding hyperlinks, if
                        any.
                        By mere use of the Platform, You shall be contracting with Energize and these Terms
                        including the policies, constitute Your binding obligations with Energize. If you do not agree
                        to be bound by the Terms, please do not use this Platform or avail any services provided
                        through this Platform.</p>
                    <b>2. Modification to the Platform Terms</b>
                    <p>Energize, at its sole discretion, reserves the right to change, modify, amend or update the
                        Platform Terms from time to time by publishing an updated version on the Platform. By
                        continuing to use the Platform you shall be deemed to accept the updated Terms and
                        agree to be bound by them.</p>
                    <b>3. Modification to the Platform</b>
                    <p>Energize reserves the right to make changes to this Platform at any time. Your usage of
                        this Platform will be subject to the Terms and policies in force at the time of such usage,
                        unless any change to these Terms or those policies is required to be made by law or
                        government authority (in which case it will apply to orders previously placed by you). If
                        any of these Terms is deemed invalid, void, or for any reason unenforceable, that Term
                        will be deemed severable and will not affect the validity and enforceability of any remaining
                        terms.
                    </p>
                    <b>4. Your Account</b>
                    <p>If you use the Platform, you are responsible for maintaining the confidentiality of your
                        account and password and for confining access to your computer to avoid unauthorised
                        access to your account. You agree to accept responsibility for all activities that occur under
                        your account and password. You should take all necessary steps to ensure that the
                        password is kept confidential and secure and shall inform us immediately if you have any
                        reason to believe that your password has become known to anyone else, or if the password
                        is being, or is likely to be, used in an unauthorised manner.
                        You should ensure that the details you provide us or are submitted by you on the Platform
                        are correct and complete and inform us immediately of any changes to the information
                        that you provided when registering. In such a situation, you shall access and update the
                        information you provided us on the Platform. You agree and acknowledge that you shall
                        use your account on the Platform to make offers to procure Services from the Service
                        Provider only for your consumption and not for resale or any other purposes. Energize
                        reserves the right to refuse access to the Platform, terminate account, remove or edit
                        content at any time without notice to You.
                        You agree that if You provide any information that is untrue, inaccurate, not current or
                        incomplete or Energize have reasonable grounds to suspect that such information is
                        untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms
                        and/or policies, Energize shall have the right to indefinitely suspend or terminate or block
                        access of your account on the Platform and refuse to provide You with access to the
                        Platform.
                        Your mobile phone number and/or e-mail address is treated as your primary identifier on
                        the Platform. It is your responsibility to ensure that your mobile phone number and your
                        email address is always up to date on the Platform. You agree to notify us promptly if your
                        mobile phone number or e-mail address changes by updating the same on Platform.
                        You agree that Energize shall not be liable or responsible for the activities or consequences
                        of use or misuse of any information that occurs under Your Account in cases, including,
                        where you have failed to update your revised mobile phone number and/or e-mail address
                        on the Platform.
                        If You share or allow others to have access to Your Account on the Platform, by creating
                        separate profiles under Your Account, or otherwise, they will be able to view and access
                        Your Account information. You shall be solely liable and responsible for all the activities
                        undertaken under Your Account, and any consequences therefrom.</p>
                    <b>5. Your Eligibility as 'User' of this Platform</b>
                    <p>Usage of this Platform is available only to person(s) who can enter into legally binding
                        contracts under The Indian Contract Act, 1872. Persons who are "incompetent to contract"
                        within the meaning of the Indian Contract Act, 1872 including but not limited to undischarged insolvent are not eligible to use the Platform.
                        Energize reserves the right to terminate Your Account and/ or refuse to provide you with
                        access to the Platform if it is brought to Energize's notice or if it is discovered that You are
                        under the age of 18 years and transacting on the Platform</p>
                    <b>6. Privacy</b>
                    <p>Please review our Privacy Policy, which also governs your use of the Platform, to
                        understand our practices. The personal information / data provided to us by you during
                        the course of usage of the Platform will be treated as strictly confidential and in accordance
                        with the Privacy Policy and applicable laws and regulations. If you object to your
                        information being transferred or used, please do not use the Platform.</p>
                    <b>7. Access to the Platform</b>
                    <p>Energize will do utmost to ensure that availability of the Platform will be uninterrupted and
                        that transmissions will be flawless. However, due to the inherent nature of the Internet
                        and Information Technology, this cannot be guaranteed. Also, your access to the Platform
                        may also be occasionally suspended or restricted to allow for repairs, maintenance, or the
                        introduction of new facilities or features or services at any time without prior notice.
                        Energize will attempt to limit the frequency and duration of any such suspension or
                        restriction.
                    </p>
                    <b>8. License to use the Platform and Your Conduct</b>
                    <p>Subject to your compliance with these Terms and payment of applicable fees, if any,
                        Energize grants you a limited, revocable and non-exclusive licence to access and make
                        personal use of this Platform, but not to download (other than page caching) or modify it,
                        or any portion of it.
                        This licence does not include any resale or commercial use of this Platform or its contents;
                        any collection and use of any services listings, descriptions, or prices; any derivative use
                        of this Platform or its contents; any downloading or copying of account information for the
                        benefit of another Service Provider; or any use of data mining, robots, or similar data
                        gathering and extraction tools.
                        This Platform or any portion of this Platform (including but not limited to any copyrighted
                        material, trademarks, or other proprietary information) may not be reproduced,
                        duplicated, copied, sold, resold, visited, distributed or otherwise exploited for any
                        commercial purpose.
                        You may not frame or use framing techniques to enclose any trademark, logo, or other
                        proprietary information (including images, text, page layout, or form) of the Energize and
                        its affiliates. You may not use any meta tags or any other "hidden text" utilising Energize's
                        or its affiliates' names or trademarks. Any such use terminates the permission or license
                        granted by Energize and/or its affiliates, as applicable to use the Platform.
                        You agree, undertake and confirm that:-
                        •You shall not use the Platform in any way that causes, or is likely to cause, the Platform
                        or access to it to be interrupted, damaged or impaired in any way.
                        •You shall not use the Platform for any of the following:
                        for fraudulent purposes, or in connection with a criminal offense or other unlawful activity.
                        oto send, use or reuse any material that does not belong to you; or is illegal, offensive
                        (including but not limited to material that is sexually explicit content or which promotes
                        racism, bigotry, hatred or physical harm), deceptive, misleading, abusive, indecent,
                        harassing, blasphemous, defamatory, libelous, obscene, pornographic, paedophilic or
                        menacing; ethnically objectionable, disparaging or in breach of copyright, trademark,
                        confidentiality, privacy or any other proprietary information or right; or is otherwise
                        injurious to third parties; or relates to or promotes money laundering or gambling; or is
                        harmful to minors in any way; or impersonates another person; or threatens the unity,
                        integrity, security or sovereignty of India or friendly relations with foreign States; or
                        objectionable or otherwise unlawful in any manner whatsoever; or which consists of or
                        contains software viruses, political campaigning, commercial solicitation, chain letters,
                        mass mailings or any "spam.
                        oto cause annoyance, inconvenience or needless anxiety.
                        •You, and not the Platform, are responsible for all electronic communications and content
                        sent from your computer to us and you must use the Platform for lawful purposes only.
                        •You shall not host, display, upload, modify, publish, transmit, update or share any
                        information which:
                        a. is misleading in any way;
                        b. infringes upon or violates any third party's rights [including, but not limited to,
                        intellectual property rights, rights of privacy (including without limitation unauthorized
                        disclosure of a person's name, email address, physical address or phone number) or rights
                        of publicity];
                        c. tries to gain unauthorized access or exceeds the scope of authorized access to the
                        Platform or to profiles, blogs, account information, bulletins, or other areas of the Platform
                        or solicits passwords or personal identifying information for commercial or unlawful
                        purposes from other users;
                        d. interferes with another user's use and enjoyment of the Platform or any other
                        individual's use and enjoyment of similar services;
                        e. refers to any Platform or URL that, in Our sole discretion, contains material that is
                        inappropriate for the Platform or any other platform, contains content that would be
                        prohibited or violates the letter or spirit of these Terms.
                        f. infringes any patent, trademark, copyright or other proprietary rights or third party's
                        trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale
                        of counterfeit or stolen products;
                        g. violates any law for the time being in force;
                        h. contains software viruses or any other computer code, files or programs designed to
                        interrupt, destroy or limit the functionality of any computer resource; or contains any
                        trojan horses, worms, time bombs, cancelbots, easter eggs or other computer
                        programming routines that may damage, detrimentally interfere with, diminish value of,
                        surreptitiously intercept or expropriate any system, data or personal information;
                        i. threatens the unity, integrity, defense, security or sovereignty of India, friendly relations
                        with foreign states, or public order or causes incitement to the commission of any
                        cognizable offense or prevents investigation of any offense or is insulting any other nation.
                        j. shall not be false, inaccurate or misleading;
                        •You shall not use any "deep-link", "page-scrape", "robot", "spider" or other automatic
                        device, program, algorithm or methodology, or any similar or equivalent manual process,
                        to access, acquire, copy or monitor any portion of the Platform or any content, or in any
                        way reproduce or circumvent the navigational structure or presentation of the Platform or
                        any content, to obtain or attempt to obtain any materials, documents or information
                        through any means not purposely made available through the Platform. Energize reserves
                        the right to bar any such activity.
                        •You shall not attempt to gain unauthorized access to any portion or feature of the
                        Platform, or any other systems or networks connected to the Platform or to any server,
                        computer, network, or to any of the services offered on or through the Platform, by
                        hacking, password "mining" or any other illegitimate means.
                        •You shall not probe, scan or test the vulnerability of the Platform or any network
                        connected to the Platform nor breach the security or authentication measures on the
                        Platform or any network connected to the Platform. You may not reverse look-up, trace or
                        seek to trace any information on any other user of or visitor to Platform, or any other
                        customer, including any account on the Platform not owned by You, to its source, or exploit
                        the Platform or any service or information made available or offered by or through the
                        Platform, in any way where the purpose is to reveal any information, including but not
                        limited to personal identification or information, other than Your own information, as
                        provided for by the Platform.
                        You shall not make any negative, denigrating or defamatory statement(s) or comment(s)
                        about Energize or the brand name or domain name used by Energize or otherwise engage
                        in any conduct or action that might tarnish the image or reputation, of Energize, or Service
                        Provider(s) on the platform or otherwise tarnish or dilute any trade or service marks, trade
                        name and/or goodwill associated with such trade or service marks, trade name as may be
                        owned or used by us. You agree that you will not take any action that imposes an
                        unreasonable or disproportionately large load on the infrastructure of the Platform or
                        systems or networks, or any systems or networks connected to Energize.
                        You shall not use any device, software or routine to interfere or attempt to interfere with
                        the proper working of the Platform or any transaction being conducted on the Platform, or
                        with any other person's use of the Platform.
                        •You shall not forge headers or otherwise manipulate identifiers in order to disguise the
                        origin of any message or transmittal You send to Us on or through the Platform or any
                        service offered on or through the Platform. You may not pretend that you are, or that You
                        represent, someone else, or impersonate any other individual or entity.
                        •You shall not use the Platform or any content for any purpose that is unlawful or
                        prohibited by these Terms of use, or to solicit the performance of any illegal activity or
                        other activity which infringes the rights of Energize and/or others.
                        •You shall at all times ensure full compliance with the applicable provisions of the
                        Information Technology Act, 2000 and rules thereunder as applicable and as amended
                        from time to time and also all applicable domestic laws, rules and regulations (including
                        the provisions of any applicable exchange control laws or regulations in force) and
                        international laws, foreign exchange laws, statutes, ordinances and regulations (including,
                        but not limited to Goods and Services Tax, Sales Tax/VAT, Income Tax, Octroi,, Central
                        Excise, Custom Duty, Local Levies) regarding Your use of Platform and Your listing,
                        purchase, solicitation of offers to purchase, and sale of services. You shall not engage in
                        any transaction in an item or service, which is prohibited by the provisions of any
                        applicable law including exchange control laws or regulations for the time being in force.
                        It is possible that other users (including unauthorized users or "hackers") may post or
                        transmit offensive or obscene materials on the Platform and that You may be involuntarily
                        exposed to such offensive and obscene materials. It also is possible for others to obtain
                        personal information about You due to your use of the Platform, and that the recipient
                        may use such information to harass or injure You. We does not approve of such
                        unauthorized usage, but by using the Platform You acknowledge and agree that We are
                        not responsible for the use of any personal information that you publicly disclose or share
                        with others on the Platform. Please carefully select the type of information that you publicly
                        disclose or share with others on the Platform.</p>
                    <b>9. E-Platform
                    </b>
                    <p>You agree, understand and acknowledge that the Platform is an online platform that
                        enables You to place offer(s) to avail Services from (Energize) on the Platform at the price
                        indicated therein at any time from any location.</p>
                    <b>10. Our Services on the Platform
                    </b>
                    <p>This Platform facilitates customers to avail any /or all of the services listed hereunder:
                        EV charging services "EV Charging Services" refers to all the services offered to the
                        Customer by the Service Provider, including the aspects of access to EV Charging Stations,
                        undertaking charging and information provided on a platform authorized by the Service
                        Provider to locate EV Charging Stations. For any customer who has entered into a separate
                        Agreement with the Service Provider, all the Terms and conditions of charging service shall
                        be governed by such Agreement between the customer and the Service Provider.
                        For the customers who have not entered into a separate Agreement with Service Provider,
                        following conditions should be adhered while availing the service1 Customer shall install and use the mobile application(s), as suggested by Service
                        Provider, on their respective mobile phone / device which shall enable them to locate the
                        nearest EV Charging Station for availing the EV Charging Services.
                        2 EV Charging Services shall be made available for the Customer only after sufficient
                        balance is maintained in the Wallet as mentioned in the platform.
                        3 Upon discharge of the Batteries, the Customer will be provided with access to the EV
                        Charging Stations maintained by the Service Provider at the Network. The station's
                        operating days and time will be available on the mobile app and shall be visible to
                        customers.
                        4 Service Provider shall have the right to revise the EV Charging Service Charges and/or
                        the method of computation of EV Charging Service Charges payable by Customer from
                        time to time. Any modification in the EV Charging Service Charges shall be communicated
                        via Platform.
                        5 Service Provider shall issue tax invoice under the provisions of GST Law for the above
                        EV Charging Service Charges plus applicable Goods and Service Tax
                        6 Customer's obligation
                        6.1 Strictly adhere to the Standard Operating Process ("SOP") adopted by the Service
                        Provider, and as updated from time to time and notified to the Customer
                        6.2 Not engage in any activity that may infringe the intellectual property rights of
                        Energize/Service Provider
                        6.3 Not in any way alter, obliterate or modify the logo, the brands, declarations and other
                        statutory notices affixed at the EV Charging Stations or any part thereof
                        6.4 Follow all types of safety related instructions and warnings communicated by the
                        Service Provider to the Customer from time to time
                        6.5 Ensure strict compliance and adherence of all the terms and conditions
                        6.6 Not damage equipment at the EV Charging Stations. In case the EV Charging Station
                        equipment is damaged by the Customer, the Customer shall be responsible to Indemnify
                        Energize/Service Provider for any loss caused to Energize due to such damage
                        11. Your Electric vehicle
                        Before placing an offer to buy the Service on the Platform, you are required to add your
                        Electric Vehicle(s) in your account.
                        You are required to upload the vehicle documents (mentioned in the Platform) such as
                        Invoice copy, Insurance and Registration certificate to prove your ownership of the electric
                        vehicle.
                        Based on your current location or any other location as entered by you in the platform,
                        the Platform will indicate the nearby charging station offered by Service Provider. You can
                        select the charging station and reserve the charging session or can directly visit the station
                        and avail charging based on availability of charger at the station.
                        All the chargers present in the network shall be visible on the platform. Any charger, which
                        is not available for charging due to pre booking or maintenance issues will also be indicated
                        on the platform. No booking shall be allowed for any charger that is not available at the
                        time of booking.
                        In case, you have more than one electric vehicle, you can attach all the vehicles to your
                        account.</p>
                    <b>12.Your order to avail charging services</b>
                    <p>You have the option to prebook/reserve a slot or charging session in advance for next 24
                        hrs or directly go to a charging station and avail the services based on availability of
                        charger. You need to maintain a minimum balance in your Wallet as mentioned in the
                        platform., only then charging services can be availed.
                        Once the booking is made, the user can use his mobile phone at the charging station to
                        avail charging against the booked order. It is mandated that the user logs in with his ID
                        and password only to charge against his booked order.
                        In an unfortunate and rare instance when your reservation is accepted and the charger is
                        not available when you reach the site, due to charger breakdown or other issues attributed
                        to Service provider, your reservation amount shall be refunded in your wallet.
                        In case of cancellation or 'no show' applicable charges as per cancellation and refund policy
                        shall be deducted. Charges for cancellation or 'No show' will be displayed at the time of
                        booking (if any) and accepted by users on the platform during booking.
                        'No show' means the user reaches the station for charging of his vehicle after the
                        reservation date or time. For example, if the booking was done till 1300 hrs of current
                        date and the user does not start charging latest by 12:59 hrs then it is assumed as 'No
                        show' and applicable deductions shall be made for the order value as indicated in the
                        platform during order booking.</p>
                    <b>13. Contract between You and Service Provider</b>
                    <p>Your request to avail services on the Platform is an offer to avail the services from the
                        charging station. When you place a request to avail the services on the Platform, subject
                        to availability and payment for the Services, you will receive a notification confirming
                        receipt of your order containing the details of your order (the "Order Confirmation
                        notification"). The Order Confirmation notification is an acknowledgement that the
                        Platform has received your order and confirms the booking at the charging station.
                        When the service is availed an email confirmation is sent to You that the service has been
                        availed and invoiced to You (the "Service offered Confirmation Email"). If you have booked
                        multiple orders then each order will have a unique order number, you may receive a
                        separate Service offered Confirmation Email for each order, and each Service offered
                        Confirmation E-mail and corresponding invoice will conclude a separate contract of service
                        between You and respective Service Provider for the service and quantity specified in that
                        Service offered Confirmation Email.
                        Your contract is with a Service provider and you confirm that the service availed by You is
                        purchased to meet the demand of your electric vehicle and not for resale or any other
                        business or legal or illegal purposes.</p>
                    <b>14.Service Pricing</b>
                    <p>Service Price can be dynamic and maximum anticipated price for the service will be
                        deducted at the time of ordering.
                        Pricing options are visible in the platform and are updated from time to time. Pricing may
                        be pay per use or users can avail various subscription plans of weekly, monthly or quarterly
                        as mentioned and updated in platform from time to time. Pay per use plan shall be based
                        on the energy consumed while subscription plans may be based on energy consumed or
                        kms travelled or both.
                        After availing the service, based on actual amount incurred or as per subscription plan or
                        as per pay per use, amount shall be deducted from the wallet. In case, the amount in the
                        wallet is less than the billed value, the user will have to upload the balance in the wallet
                        and pay, else the same will be deducted in the next transaction initiated by the user.
                        All prices are inclusive of VAT/CST, Goods and Services Tax ("GST"), duties and cesses as
                        applicable - unless stated otherwise.</p>
                    <b>15. Taxes</b>
                    <p>You shall be responsible for payment of all fees/costs/ charges associated with the Services
                        from Service Provider(s) and you agree to bear any and all applicable taxes including but
                        not limited to VAT/CST, Goods and Services Tax ("GST"), duties and cesses etc.</p>
                    <b>16. Payment</b>
                    <p>You shall be making the payment only through the wallet created in the platform for you,
                        at the time of registration for placement of order. Customers shall ensure maintenance of
                        minimum balance required for availing the service. Platform will accept the payment
                        through the integrated payment gateways into the wallet only. Your reservation/booking
                        shall be confirmed after successful payment transactions for reservation fee from the
                        wallet. In case the amount is loaded in the wallet via any payment method from payment
                        gateway and the same is successful, then subject to such amount being sufficient for
                        availing the requisite service, the Customer may reserve the order against the amount in
                        wallet. In case, due to technical issues, payment is not Successful, the amount will not be
                        transferred into the wallet and you cannot subsequently book reserve the order due to
                        insufficient balance in wallet. In case, amount has been deducted from Your bank account
                        while doing the online payment, Platform checks the status at periodic intervals and if the
                        response received is successful, the amount will be loaded in the wallet and you can make
                        the payment for the reservation.
                        In case, Platform has not received successful status against the wallet loading request,
                        the amount will be refunded in Your respective bank account within 7-10 working days.
                    </p>
                    <b>17. Cancellation of Offer to avail the service</b>
                    <p>You may cancel your reservation to avail the service before Your Order execution time.
                        Cancellation will be handled as per cancellation and refund policy.</p>
                    <b>18. Service Return
                    </b>
                    <p>Service shall not be returned to the Service provider under any circumstances.</p>
                    <b>19. Copyright, authors' rights and database rights</b>
                    <p>All content included on the Platform, such as text, graphics, logos, button icons, images,
                        audio clips, digital downloads, data compilations, and software, is the property of Energize
                        and/or its affiliates or its content suppliers and is protected by India and international
                        copyright, authors' rights and database right laws. The compilation of all content on this
                        Platform is the exclusive property of Energize, its affiliates and its content suppliers and is
                        protected by laws of India and international copyright and database right laws. All software
                        used on this Platform is the property of Energize, its affiliates or its software suppliers and
                        is protected by India and international copyright and author' rights laws. You shall not
                        systematically extract/ or re-utilise parts of the contents of the Platform. In particular, you
                        shall not utilize any data mining, robots, or similar data gathering and extraction tools to
                        extract (whether once or many times) for re-utilisation of any substantial parts of this
                        Platform. You shall also not create and/ or publish your own database that features
                        substantial (e. g. prices and/ or service listings) parts of this Platform.</p>
                    <b>20. Trademarks</b>
                    <p>Trademarks indicated on the Platform are trademarks or registered trademarks of Energize
                        or its affiliates in the jurisdictions. Graphics, logos, page headers, button icons, scripts and
                        service names are the trademarks or trade dress of Energize. Energize's trademarks and
                        trade dress may not be used in connection with any service that is not Energize's, in any
                        manner that is likely to cause confusion among customers, or in any manner that
                        disparages or discredits Energize. All other trademarks not owned by Energize that appear
                        on this Platform are the property of their respective owners, who may or may not be
                        affiliated with, connected to, or sponsored by Energize.</p>
                    <b>21. Disclaimer</b>
                    <p>You acknowledge and undertake that you are accessing the services on the Platform and
                        transacting at your own risk and are using your best and prudent judgment before entering
                        into any transactions through the Platform. You further acknowledge and undertake that
                        you will use the Platform to purchase services only for your consumption in the specified
                        assets and not for resale or any other purposes. Energize shall neither be liable nor
                        responsible for any actions or inactions of service provided nor any breach of conditions,
                        representations or warranties by the Service provider and hereby expressly disclaim any
                        all responsibility and liability in that regard. Energize shall not mediate or resolve any
                        dispute or disagreement between you and other service providers.
                        Energize further expressly disclaim any warranties or representations (express or implied)
                        in respect of quality, suitability, accuracy, reliability, completeness, timeliness,
                        performance, safety, merchantability, fitness for a particular purpose, or legality of the
                        services listed or displayed or transacted or the content (including service or pricing
                        information and/or specifications) on the Platform. While Energize has taken precautions
                        to avoid inaccuracies in content, this Platform, all content, information (including the price
                        of service), software, services and related graphics are provided as is, without warranty
                        of any kind. Energize does not implicitly or explicitly support or endorse the sale or
                        purchase of any service on the Platform. At no time shall any right, title or interest in the
                        service offered through or displayed on the Platform vest with Energize nor shall Energize
                        have any obligations or liabilities in respect of any transactions on the Platform.</p>
                    <b>22. Indemnity and Release</b>
                    <p>You shall indemnify and hold harmless Energize and/or its affiliates and/or their respective
                        officers, directors, agents and employees, from any claim or demand, or actions including
                        reasonable attorney's fees, made by any third party or penalty imposed due to or arising
                        out of your breach of these Terms or any document incorporated by reference, or your
                        violation of any law, rules, regulations or the rights of a third party.
                        You hereby expressly release Energize and/or its affiliates and/or their respective officers,
                        directors, agents and employees, from any cost, damage, liability or other consequence
                        of any of the actions/inactions of the vendors and specifically waiver any claims or
                        demands that you may have in this behalf under any statute, contract or otherwise.</p>
                    <b>23. Communications</b>
                    <p>When you visit the Platform, you are communicating with us electronically. You will be
                        required to provide a valid phone number while placing an order with us. We may
                        communicate with you by email, SMS, phone call or by posting notices on the Platform or
                        by any other mode of communication. For contractual purposes, you consent to receive
                        communications (including transactional, promotional and/or commercial messages), from
                        us with respect to your use of the Platform and/or your order placed on the Platform.</p>
                    <b>24. Losses</b>
                    <p>Energize shall not be responsible for any business loss (including loss of profits, revenue,
                        contracts, anticipated savings, data, goodwill or wasted expenditure) or any other indirect
                        or consequential loss to you due the usage of the Platform.</p>
                    <b>25. Force Majeure</b>
                    <p>Energize shall not be held responsible for any delay or failure to comply with its obligations
                        under these Terms if the delay or failure arises from any cause which is beyond its
                        reasonable control or acts of God, insurrection, action of pirates, war declared or
                        undeclared, general transport strikes or break down, pandemic, lockdown, shortage in
                        supply of services or equipment etc These Terms does not affect your statutory rights.
                    </p>
                    <b>26. Waiver</b>
                    <p>If you breach these conditions and we take no action, we will still be entitled to use our
                        rights and remedies in any other situation where you breach these conditions</p>
                    <b>27. Governing law and Jurisdiction
                    </b>
                    <p>These conditions are governed by and construed in accordance with the laws of India. You
                        agree, as we do, to submit to the exclusive jurisdiction of the courts at Kolkata.</p>
                    <b>28. Our Details</b>
                    <p>This Platform is operated by Energize. For any query, you can contact us by writing to
                        query@energizecharging.com or also visit our website www.energizecharging.com</p>
                </div>
            </div>
            <Footer />
        </div >
    )
}
